export enum ErrorCodes {
  ROOMING_LIST_NOT_FOUND = 'ROOMING_LIST_NOT_FOUND',
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  DUPLICATE_BOOKING = 'DUPLICATE_BOOKING',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED'
}
